### ISSUE TITLE
Update Nuget ServiceBase

### ISSUE THREAD

**Issue by banarualexandru** [aruss/IdentityBase#17]
Hello

Thank you for a great job by putting all the stuff of an IdentityServer together. I faces a problem on finding the 1.1.21 version of ServiceBase library. Until found the ling where I can found current version. 

Do you plan to update nuget package for the ServiceBase library? I'm sure that this will help for new people who will try your package.

Thank you!

**Comment by aruss** [comment]
Hi, 
there are CI feeds of the master branch you could use. 

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="IdentityBase Dev Feed" value="https://ci.appveyor.com/nuget/identitybase-jyp5a0f2j449" />
    <add key="ServiceBase Dev Feed" value="https://ci.appveyor.com/nuget/servicebase-v2ipc63cfj6u" />
    <add key="Identity* Dev Feed" value="https://www.myget.org/F/identity/" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
I didn't done much distribution stuff yet, since I rewriting couple things to enable easier extension development. We use it internally for couple project with different requirements so I discovered couple issues, as soon they are solved there will be better startup guide.
